django_intro/urls.py
from django.contrib import admin
from django.urls import path, include
# from django_app import views   # url 파일은 views를 이동시킴
from app_intro import views   # 설정한 앱이름의 폴더 안에 있는 views 파일 참고

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),   # url이 오면 메소드를 실행해야 한다
    path('lunch/', views.lunch),
    path('lotto/', views.lotto),
    path('hello/<str:name>/', views.hello),   # 이름이 들어오면 hello를 출력함
    path('cube/<int:num>', views.cube),
    path('todos/', include('todo.urls'))
    
]

todo/urls.py
from django.urls import path
from . import views   # 현재 폴더의 views.py 추가

app_name = 'todo'

urlpatterns = [
    # 이 아래 들어가는 url들의 앞에 todos/가 생략되었음
    path('', views.index),
    path('new/', views.new),   # todo/new가 오면 todo new를 실행함
    path('create/', views.create), 
    path('<int:id>/', views.read),
    path('todo_create/', views.todo_create),
    path('<int:id>/update', views.update, name='update'),
    path('<int:id>/delete', views.delete, name='delete'),
    
]

app_intro/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length=50)
    deadline = models.DateField()

    def __str__(self):
        return self.title

app_intro/views.py
from django.shortcuts import render
import random

# Create your views here.
def index(request):
    return render(request, 'index.html')
    
def lunch(request):
    menu_list = ['20층', '김밥카페', '시골집']
    pick = random.choice(menu_list)
    return render(request, 'lunch.html', {'pick': pick})
    
def lotto(request):
    lotto_list = range(1, 46)
    pick = random.sample(lotto_list, 6)
    return render(request, 'lotto.html', {'pick': pick})
    
def hello(request, name):
    return render(request, 'hello.html', {'name': name})

def cube(request, num):
    multi = num**3
    return render(request, 'cube.html', {'multi': multi})

todo/views.py
from django.shortcuts import render, redirect
from todo.models import Todo

# Create your views here.
def index(request):
    todos = Todo.objects.all()
    return render(request, 'todo/index.html', {'todos' : todos})


def new(request):
    return render(request, 'todo/new.html')  # 사용자가 입력할 수 있는 폼 만들기

# read / create - new.html을 통한 create.html로 출력(get 방식)    
def create(request):
    title = request.POST.get('title')
    deadline = request.POST.get('deadline')
    todo = Todo(title=title, deadline=deadline)    
    todo.save()   # db.session.add() + db.session.commit()과 동일    
    
    return redirect('/todos/')

def read(request, id):
    todo = Todo.objects.get(id=id)
    return render(request, 'todo/read.html', {'todo': todo})
    
# read/create 합치기 - todo_create.html을 통한 get 방식 입력 후 todo_create.html로 출력
def todo_create(request):
    if request.method == "POST":
        title = request.POST.get('title')
        deadline = request.POST.get('deadline')
        # Todo(title = title, deadline = deadline)
        # todo.save()
        Todo.objects.create(title=title, deadline=deadline)  # 위 2문장을 합친 것(save가 자동으로 됨)
        return redirect('/todos/')
    else:
        return render(request, 'todo/todo_create.html')
    

def update(request, id):
    todo = Todo.objects.get(id=id)  # 기존 id에 해당하는 objects(todo)를 가져옴
    if request.method == "POST":
        # 저장로직
        todo.title = request.POST.get('title')
        todo.deadline = request.POST.get('deadline')
        todo.save()
        
        return redirect('/todos/')
        
    else:
        # 폼 보여주기(버튼을 누르면 get 방식)
        deadline = todo.deadline.strftime("%Y-%m-%d")  # datetime은 datetime 객체이므로 형식이 지정되어 있음
      # deadline = "{}-{}-{}".format(todo.deadline.your, todo.deadline.month, todo.deadline.day)   # 둘 다 가능
        return render(request, 'todo/update.html', {'todo': todo, 'deadline': deadline})
        
        
def delete(request, id):
    todo = Todo.objects.get(id=id)
    todo.delete()
    return redirect('/todos/')

app_intro/templates/cube.html
{{multi}}

app_intro/templates/hello.html
{{name}}

app_intro/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>여기는 인덱스입니다.</h1>
</body>
</html>

app_intro/templates/lotto.html
{{pick}}

app_intro/templates/lunch.html
{{pick}}

todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <a href='/todos/new'>글 작성</a>
    <a href='/todos/todo_create'>합쳐진 로직</a>
    {% block body_block %}
    
    {% endblock %}
</body>
</html>

todo/templates/todo/index.html
{% extends 'todo/base.html' %}

{% block body_block %}
    <h1>todo의 인덱스입니다.</h1>
    {% for todo in todos %}
        <h1>{{todo.title}}</h1>
        <h5>{{todo.deadline}}</h5>
        <a href="/todos/{{todo.id}}/">글보기</a>
    {% endfor %}

{% endblock %}

todo/templates/todo/new.html
{% extends 'todo/base.html' %}   <!--그냥 base.html로 하면 파일을 못 찾는다-->

{% block body_block %}
<form action="/todos/create/", method="post">
    {% csrf_token %}   <!--CSRF 공격 막기-->
    <input type="text" name="title">
    <input type="date" name="deadline">
    <input type="submit">
</form>
{% endblock %}

todo/templates/todo/read.html
{% extends 'todo/base.html' %}

{% block body_block %}
    <h1>{{todo.title}}</h1>
    <h4>{{todo.deadline}}</h4>
    <a href="/todos/{{todo.id}}/update">수정</a>
    <!--<a href="{% url 'todo:update' id=todo.id %}">또 다른 수정</a>-->
    <a href="/todos/{{todo.id}}/delete">삭제</a> 
{% endblock %}

todo/templates/todo/todo_create.html
{% extends 'todo/base.html' %}

{% block body_block %}
<form action="/todos/todo_create/", method="post">
    {% csrf_token %}
    <input type="text" name="title">
    <input type="date" name="deadline">
    <input type="submit">
</form>
{% endblock %}

todo/templates/todo/update.html
{% extends 'todo/base.html' %}

{% block body_block %}
<form action="/todos/{{todo.id}}/update" method="post">
    {% csrf_token %}
    <input type="text" name="title" value="{{todo.title}}"/>  <!--먼저 값을 불러와 넣기-->
    <input type="date" name="deadline" value="{{deadline}}"/>
    <input type="submit">
</form>
{% endblock %}